### ISSUE TITLE
Build of kmax image fails

### ISSUE THREAD

**Issue by duckymirror** [ekuiter/torte#2]
Building the kmax image currently fails. The reason seems to be that Python 3.6 is used, but the `dd` dependency (resolved to version 0.6.0) requires Python >= 3.11.

Full build log: [build-log.txt](https://github.com/ekuiter/torte/files/13793014/build-log.txt)

**Comment by ekuiter** [comment]
Thanks for the report! I'll look into it.

**Comment by ekuiter** [comment]
I bumped the version of kmax, it should work now (I tested it with `default.sh` on a fresh ubuntu virtual machine).
